import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WalletProvider } from "@/context/WalletContext";
import { MultiGiveawayProvider } from "@/context/MultiGiveawayContext";
import { ActiveGiveawayProvider } from "@/context/ActiveGiveaway";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const getContractAddress = () => {
    // Check which network we're using
    const network = process.env.REACT_APP_NETWORK || process.env.REACT_APP_DEFAULT_NETWORK || 'SEPOLIA';
    
    // Return the appropriate contract address based on network
    if (network === 'SEPOLIA') {
      return process.env.REACT_APP_SEPOLIA_CONTRACT_ADDRESS;
    } else if (network === 'POLYGON') {
      return process.env.REACT_APP_POLYGON_CONTRACT_ADDRESS;
    } else if (network === 'MUMBAI') {
      return process.env.REACT_APP_MUMBAI_CONTRACT_ADDRESS;
    }
    
    // Default to Sepolia contract address
    return process.env.REACT_APP_SEPOLIA_CONTRACT_ADDRESS;
  };

  const contractAddress = getContractAddress();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WalletProvider>
          <MultiGiveawayProvider contractAddress={contractAddress}>
         <ActiveGiveawayProvider>
         {children}
         </ActiveGiveawayProvider>
          </MultiGiveawayProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
